### ISSUE TITLE
does the caffemodel keep the same with the old one  when  prototxt changed

### ISSUE THREAD

**Issue by dashan336** [TLESORT/YOLO-TensorRT-GIE-#5]
hi, 
the prototxt is  changed ( from yolo_small_deploy.prototxt to yolo_small_modified.prototxt) . Does the caffemodel also get some changes? Or the caffemodel of yolo_small_modified.prototxt  is the same with that of  yolo_small_modified.prototxt?

**Comment by dashan336** [comment]
relu+scale replaced leaky relu. Will this operation bring in some new parameters  ? I'm afraid that will make the caffemodel change. will you please answer this ?

**Comment by TLESORT** [comment]
Hi Dashan336, the caffemodel keeps the same for yolo_small_deploy.prototxt  and yolo_small_modified.prototxt :)
